/*
 * config.hpp
 *
 *  Created on: Feb 26, 2013
 *      Author: ThienLong
 */

#ifndef CONFIG_HPP_
#define CONFIG_HPP_

#define SOLT_TORRENT_STD_CPLUSPLUS_11
//#define SOLT_TORRENT_START_ON_ADD
#define SOLT_TORRENT_CLEAR_PIECE_DEADLINE
//#define SOLT_TORRENT_ABORT_PB_BY_PIECE_PICKER
#define SOLT_TORRENT_MAX_CONNECTION_PER_TORRENT 50
#define SOLT_TORRENT_GLOBAL_MAX_CONNECTION 200
#define SOLT_TORRENT_MAX_HALF_OPEN 100
#endif /* CONFIG_HPP_ */
